### ISSUE TITLE
I'm not seeing any Swiss German keyboard...

### ISSUE THREAD

**Issue by Zero7007** [Dukweeno/Duckuino#102]
## I. Environment

- Platform: Laptop
- OS: MacOS
 - Browser: Chrome

## II. My problem

I would love to see some swiss_german layout, or at least a way to configure myself this kind of layout...

Thank you for your time.

**Comment by Nurrl** [comment]
Hello @Zero7007, it's a bit weird how to configure keys, it haves something to do with Key Codes, when I did it, I did it by **trial and error** until I finally done it.
